---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

We are all here for a reason on a particular path  
You don't need a curriculum to know that you're a part of the math  
Cats think I'm delirious but I'm so damn serious  
That's why I expose my soul to the globe; the world  
I'm trying to make it better for these little boys and girls  
I'm not just another individual  
My spirit is a part of this that's why I get spiritual  
But I get my hymns from Him  
So it's not me, it's He that's lyrical  
I'm not a miracle, I'm a heaven-sent instrument  
My rhythmatic regiment navigates melodic notes  
For your soul and your mental  
That's why I'm instrumental, vibrations is what I'm into  
Yeah I need my loot by rent day  
But that ain't what gives me the heart of Kunta Kinte  
I'm trying to get us "us free" like Cinque  
I can't stop, that's why I'm hot  
Determination, dedication, motivation  
I'm talking to you of my many inspirations  
When I say I can't let you or self-down  